### ISSUE TITLE
Intial Roadmap

### ISSUE THREAD

**Issue by FSMaxB** [communityvi/communityvi#1]
* Backend-Refinement
	* [ ] pull register out or `server.rs`
	* [ ] handle close correctly on register
	* [ ] enforce message numbers (via number in ClientConnection)
	* [ ] remove all Messages that have `#[serde(skip)]` in general
* Client niceties
	* [ ] send on enter
	* [ ] clear text-field on send
	* [ ] prevent XSS
	* [ ] register only once?
* [ ] client left the room
* [ ] enforce name to be non-empty + unique

Milestones:
* [ ] synchronized counter (without skipping, play pause)
* [ ] skipping, play/pause
* [ ] load and play file from disk
* [ ] YouTube
